version: "3.9"
networks:
  default:
    external: 
      name: unicon-ivenza
services:
  ivenza-auth-migration-tool:
    container_name: ivenza-auth-migration-tool 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://ivenza:ivenza@db:3306/ivenza
      - AUTHORITY=http://keycloak:8080/realms/master
      - KEYCLOAK_CLIENT_ID=admin-cli
      - KEYCLOAK_ADMIN_USERNAME=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - ADMIN_BASE_URL=http://keycloak:8080/admin/realms/delihome
      - CLIENT_ID=17873d79-f666-487a-ab9f-239fabbeb24d
