version: '3.9'
networks:
  default:
    external:
      name: unicon-ivenza
services:
  keycloakdb:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${KEYCLOAK_DATABASE_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DATABASE_NAME}
    volumes:
      - unicon-kc_pg:/var/lib/postgresql/data

  keycloak:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
      - KEYCLOAK_VERSION=${KEYCLOAK_VERSION}

    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloakdb
      - KC_DB_USERNAME=${KEYCLOAK_DATABASE_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloakdb

volumes:
  unicon-kc_pg:
