name: "Publish keycloak image to ACR"

env:
  MICROSERVICE_NAME: keycloak
  DOCKERFILE: docker/Dockerfile
  ACR_URL: uniconcreation.azurecr.io
  KEYCLOAK_VERSION: 25.0.2

on:
  workflow_dispatch:
  release:
    types: 
      - prereleased
      - released
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          
          IMAGE_TAG="${{ github.event.release.tag_name || github.ref_name }}"
          if [[ "${{ github.event.release.prerelease }}" != "false" ]];
            then IMAGE_TAG="$IMAGE_TAG-nightly";
          fi
          docker build . \
            --tag ${{ env.ACR_URL }}/${{ env.MICROSERVICE_NAME }}:$IMAGE_TAG \
            --build-arg KEYCLOAK_VERSION="${{ env.KEYCLOAK_VERSION }}" \
            --label ivenza.build="${{ github.run_number }}" \
            --label ivenza.ref="${{ github.ref_name }}" \
            --label ivenza.commit="${{ github.sha }}" \
            --file ${{ env.DOCKERFILE }}
          docker push ${{ env.ACR_URL }}/${{ env.MICROSERVICE_NAME }}:$IMAGE_TAG

